### ISSUE TITLE
KeyboardInterrupt when exit from capturing packets

### ISSUE THREAD

**Issue by dragonxtek** [shramos/polymorph#17]
I upgraded to 2.0.4 but when I press Ctrl+C, polymorph crashes
![Selection_999(920)](https://user-images.githubusercontent.com/10552658/95607363-0137aa80-0a32-11eb-95dc-ad61070a2622.png)

**Comment by shramos** [comment]
Hello @dragonxtek, 

It seems that you have pressed Ctrl+C twice, thus interrupting the parsing process of the captured network packets. Press Ctr+C once and wait for Polymorph to finish parsing the captured packets. 

I will add a small fix that will capture that exception and finish the parsing process without leaving the application.

Thanks!

**Comment by dragonxtek** [comment]
Hi again,
I updated to the new version (2 minutes ago) and now I got this:

![Selection_999(925)](https://user-images.githubusercontent.com/10552658/95612906-7c04c380-0a3a-11eb-9142-78bd1cc16829.png)

Thanks!

**Comment by shramos** [comment]
It's the same error as the previous one, I haven't updated to the new version yet.

**Comment by shramos** [comment]
This issue is already solved in the new update 2.0.5 of Polymorph

**Comment by dragonxtek** [comment]
The error still appears

![image](https://user-images.githubusercontent.com/10552658/95618314-2e408900-0a43-11eb-830f-df601753c0fb.png)
